### PR TITLE
configure max_item_size for queryFrontEnd and Store deployments 

### PR DESCRIPTION
**Pull request by subbarao-meduri**
when maxItemSize is specified

### CODE REVIEW

**Comment by marcolan018** [comment]
we should have a pr in observatorium repo before this one, since it uses the jsonnet file there?

**Comment by subbarao-meduri** [comment]
> @subbarao-meduri we should have a pr in observatorium repo before this one, since it uses the jsonnet file there?

Per our conversation, `max_item_size` does not exist in upstream observatorium CRD, and this is an ACM extension. We forked community observatorium as `stolostron/observatorium-deployment` to drive this change.

**Pull request merged**
