### PR TITLE
Updated OWNERS file for release-2.7

### PR DESCRIPTION
**Pull request by dislbenn**
https://issues.redhat.com/browse/ACM-2363
Signed-off-by: dislbenn <dbennett@redhat.com>

### CODE REVIEW

**Review by subbarao-meduri — APPROVED** [review]
/lgtm

**Comment by dislbenn** [comment]
/override ci/prow/e2e-kind

Overriding this job since this PR is to update the OWNERS file for this repo. We will need to debug the failure at a later time.

**Pull request merged**
