### PR TITLE
Updated COMPONENT_VERSION file for release-2.8

### PR DESCRIPTION
**Pull request by dislbenn**
Signed-off-by: dislbenn <dbennett@redhat.com>

### CODE REVIEW

**Review by subbarao-meduri — APPROVED** [review]
/lgtm

**Comment by dislbenn** [comment]
/override ci/prow/e2e-kind

To prevent this PR from being blocked, I will override the ci/prow/e2e-kind test. It seems like there is an issue occurring where the test is timing out at the same spot:

 job.batch/observatorium-up-metrics-tls created
error: timed out waiting for the condition on jobs/observatorium-up-metrics-tls 

We've tried increasing the timeout period to 10m; however, the failure is still occurring. For this PR, we are only updating the COMPONENT_VERSION; therefore, I will open up a task for this failure and attempt to fix the issue within a separate PR.

**Pull request merged**
